# Generated by Django 2.2.10 on 2020-10-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compaignmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignName', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('opens', models.CharField(max_length=200, null=True)),
                ('clicks', models.ImageField(max_length=12, null=True, upload_to='')),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
