# Generated by Django 2.2.10 on 2020-10-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaignmodel',
            name='clicks',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
